### ISSUE TITLE
Make Faker.Date.date_of_birth/1 with valid dates

### ISSUE THREAD

**Issue by igas** [igas/faker#100]
Right now dob can't be on 30 or 31. Suggestion is to introduce private function `to_valid_day(date, month, year)` and return maximum possible date, for example:

`to_valid_day(31, 9, 2017) # => 30`

In case of February we'll need to check for leap year.

**Comment by tobyhinloopen** [comment]
Isn't there some kind of common library that can represent a range of dates (EG a range from `17 years ago` to `18 years ago`) so we can just `Enum.random` it?

**Comment by lauraannwilliams** [comment]
Date Ranges are a 1.6 feature from the looks of things
https://github.com/elixir-lang/elixir/blob/741b6adbd8c4be1735dc9c605b8d5cdc7b73bc1a/lib/elixir/lib/calendar/date_range.ex#L1

Perhaps something like this https://medium.com/@natetsai/implementing-date-ranges-in-elixir-384460f3b7fa ?

**Comment by tobyhinloopen** [comment]
Merged
