### ISSUE TITLE
Can you add a faker for file systems ?

### ISSUE THREAD

**Issue by lowks** [igas/faker#102]
As the title suggest, can you add a module to fake filesystems ? -> files and directories.

**Comment by tobyhinloopen** [comment]
Something like `Faker.File` with things like:

```elixir
base_name  # A random directory- or filename without extension
file_name # base_name <> extension
file_path # directory_path <> base_name <> extension
image_path # directory_path <> base_name <> image_extension
image_extension # ".png", ".jpg", ".jpeg", ".gif", ".tiff", ".bmp"
executable_extension # ".jar", ".exe", ???
executable_path # directory_path <> base_name <> executable_extension
executable_name # base_name <> executable_extension
extension # Enum.random [image_extension, executable_extension, ...]
directory_name # alias of `base_name`
directory_path # a random amount of directory_name, joined by `/`, with optional inclusions of `/./`, `/../`, `//`, etc
```

**Comment by lowks** [comment]
Yeah. It would be very nice. Now in order to test my path library I create real directories and commit that in my code :-(

**Comment by tobyhinloopen** [comment]
Faker would generate file**names** here, not actual files.

Besides, feel free to add it yourself, ofcourse

**Comment by lowks** [comment]
Filenames would be cool like how one would mock `os.lsdir` in Python.

**Comment by tobyhinloopen** [comment]
I think it would be a reasonable addition. You could create a PR if you'd like

**Comment by lowks** [comment]
I will study the code first. Heads up I am a slow coder.



[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

**Comment by tobyhinloopen** [comment]
Slow & steady wins the race, hah

If you need any help, feel free to ask :)

**Comment by lowks** [comment]
okay



[image: Low Kian Seong on about.me]

Low Kian Seong
about.me/lowkianseong
  <http://about.me/lowkianseong>

**Comment by tobyhinloopen** [comment]
@lowks Do note that quoting from mail in your case includes unsubscribe urls from the e-mails

**Comment by orieken** [comment]
Looks like a lib already does this sort of thing 
https://github.com/CargoSense/briefly
https://github.com/CargoSense/briefly#example
```
## Example

Create a file:

```elixir
{:ok, path} = Briefly.create
File.write!(path, "Some Text")
content = File.read!(path)
# When this process exits, the file at `path` is removed
```

Create a directory:

```elixir
{:ok, path} = Briefly.create(directory: true)
File.write!(Path.join(path, "test.txt"), "Some Text")
# When this process exits, the directory and file are removed
```

See [the documentation](http://hexdocs.pm/briefly/Briefly.html#create/1) to see
the options that available to `Briefly.create/1` and `Briefly.create!/1`.
```
