### ISSUE TITLE
Issue with indeterminate results using `image_url`

### ISSUE THREAD

**Issue by lackdaz** [igas/faker#108]
https://github.com/igas/faker/blob/42c1e36a4d8420ce05133dc8905cd3b178d79b24/lib/faker/internet.ex#L95

needs to be corrected to

```elixir
defp image_url(0), do: "https://placekitten.com/#{:crypto.rand_uniform(1, 1024)}x#{:crypto.rand_uniform(1, 1024)}"
```

**Comment by igas** [comment]
Hi @lackdaz and @sotojuan,

I've just checked their website http://placekitten.com/ and according to the example it's correct URL, but I couldn't load any images.

Can you please check from your side? Maybe we need to drop this one.

**Comment by lackdaz** [comment]
I've checked and it is indeed working. My bad and will drop the issue

**Comment by sotojuan** [comment]
And I will close my PR.
