### ISSUE TITLE
Remove JSON programming

### ISSUE THREAD

**Issue by whatyouhide** [igas/faker#12]
As mentioned in #9, it's probably better to entirely remove JSON programming and only use JSON in order to store **data**.

My main concern is this: are fake data structures similar in all languages? I see you created a "team" object, which has the form `[state] [creature]`. In Italian for example, that would be `[creature] [state]`.

What I would do is create a module for each fake data type (e.g., `Faker.Team`) to act as a namespace, and then create submodules of that namespace for each locale (e.g., `Faker.Team.En`). Then we could just delegate the functions to the right locale from `Faker.Team` (I think this could be done at compile-time, actually). This as the advantage of keeping everything separate, with a directory structure like this:

```
lib/
|-- en/
    |-- team.ex
|-- it/
    |-- team.ex
team.ex
```

or

```
lib
|-- team.ex
|-- team/
    |-- en.ex
    |-- it.ex
```

I'm pretty sure this solution would still need to start a `:faker` application though; this is mentioned as something to remove (and I agree!) on #9 again.

Did you have something in mind?

**Comment by vforvova** [comment]
:+1:

**Comment by igas** [comment]
Wow! @whatyouhide you read my thoughts! I already start some experiments to do this, take a look at https://github.com/igas/faker/commit/2ab92616117c1e0eb92ce00a3623f3804c18e7e6
I want to minimize metaprogramming as much as possible, but for now I stuck with https://github.com/igas/faker/blob/5e72087db4d071308eddfb0881671f97b3730369/priv/address.json#L9-L14 we can't just hardcode it to function cause it interpolate every value of list. For now in my head some macro which take a name & list and made main function which randomly pick one of internal function with value from this list, for example after compile it looks like:

```
def city do
  city(:crypto.rand_uniform(0, 2))
end

def city(0) do
  "#{city_prefix} #{Faker.Name.first_name}#{city_suffix}"
end

def city(1) do
  "#{city_prefix} #{Faker.Name.first_name}"
end
```

I like our approach with different modules, I don't see it in any other implementations. It's awesome what we can directly call `Faker.Name.Ru.full_name` and `Faker.Name.Fr.full_name` inside one test without changing locale(like in ruby for example) and test international support of app. Also it's more customizable, in Russian for example male and female names are different, and we can add `male_last_name` and `female_last_name` without touching other.

Also storing can be moved to module attributes, then we can omit any dependencies of faker.

When I mention application I mean do not add it to mix like it described in https://github.com/igas/faker#troubleshooting and just start it inside test helper with default locale which will pick right module. something like `Faker.start(:it)` and later any function in `Faker.Name` will call `Faker.Name.It` or `Faker.start(:ru)` respectively `Faker.Name` => `Faker.Name.Ru`.

Looking forward for your feedback.

**Comment by whatyouhide** [comment]
I like the `city/0` + `city/1` approach you proposed in your comment. That's definitely the direction I'd like this library to go towards.

As for starting the application, I don't know what's the best solution. Another idea could be to just create a Faker "object" that you can pass as the first argument to `Faker` functions (e.g., in a [Exredis](https://github.com/artemeff/exredis)-like fashion):

``` elixir
faker = Faker.new(:ru)
faker |> Faker.city #=> "Moscow"
```

I'm not a fan of this approach since it requires a reference to that `faker` object at all times. On the other hand, Fake` is a library meant for generating fake data to store (development) or to test stuff against (testing), so users could, for example, just create a faker object as a module attribute in their tests and use the same object at all times.
This approach, however, makes `Faker` completely independent from any configuration/Mix/application. Nice!

In general, I think the approach with the application is not bad per se, but maybe we should change the README so that the `:faker` application is added only in the right environments (not in `:prod`).

``` elixir
def application do
  [
    applications: [:logger] ++ (if Mix.env ,
    env: [locale: :en]
  ]
end

defp applications do
  apps = [:logger]
  if Mix.env == :dev or Mix.env == :test, do: [:faker | apps], else: apps
end
```

This way users don't accidentally start the `:faker` application (taking resources and so on) on their production environment, which probably doesn't need Faker anyways.

Let me know what you think!

(Note: when I talk about "object", I clearly mean something like a struct, not a real object :) I think something like `%Faker{}` should do the trick)

**Comment by igas** [comment]
I think it can be written this way:

```elixir
def application do
  [applications: applications(Mix.env)]
end

defp applications(),  do: [:logger]
defp applications(:test), do: [:faker, applications()]
```

I think every time pass object too verbose. Another longterm plans is to add `Agent`, you know, often you need uniq value, we can store/clean value on each test and regenerate if it already present. It's something I also don't see in any other implementations. If you familiar with ruby FactoryGirl, we can run `FactoryGirl.create_list(:category, 50)` and sometimes tests fails because `name` not unique.

**Comment by whatyouhide** [comment]
Premise: I left a dangling piece of code in the example above, fixed that.

I actually am pretty familiar with FactoryGirl, but, as I see it, FactoryGirl is *very* far from Faker. FactoryGirl is test oriented, and is focused on creating model instances (and **persisting** them), while Faker is development oriented, focused on providing stub data to fill your database with. At least, that's what I've always known Ruby's Faker (the one you mention as an inspiration in the README) for.

With that in mind, Faker shouldn't provide a `Faker.create_list(:address)` method since that's not its purpose. Users of Faker should just:

``` elixir
Enum.each 1..50, fn(_i) ->
  Faker.address |> PersistenceLayer.save_to(:addresses)
end
```

Uniqueness and other constraints should not be Faker's concerns, but the user's application's (as with Ruby Faker, again). That's why I was suggesting to create a `%Faker{}` object to pass around: it's not very verbose and it's only done in code whose purpose is to stub data (not production/testing code).

**Comment by igas** [comment]
I'm still not sure about passing struct.

```elixir
defmodule Forge do
  use Blacksmith

  faker = Faker.new(:fr)
  register :user,
    type: :map,
    first_name: faker |> Faker.Name.first_name,
    last_name: faker |> Faker.Name.first_name,
    email: faker |> Faker.Internet.email,
    description: faker |> Faker.Lorem.sentence
end
```

versus

```elixir
defmodule Forge do
  use Blacksmith

  register :user,
    type: :map,
    first_name: Faker.Name.first_name,
    last_name: Faker.Name.first_name,
    email: Faker.Internet.email,
    description: Faker.Lorem.sentence
end
```

About uniqueness, I don't mean persistence, it's only about data generation. Very dirty example:

```elixir
Faker.track_uniq(Faker.Internet, :email)
Forge.user_list 50
Faker.reset_uniq
```

We don't persist anything or whatever, we just taking care that data in some generation sequence uniq. If it'll be solved by user, it's again will be verbose, to check value exist/regenerate/track. Anyway it's longterm and I'm also not sure about that. So let's forget about it for now.

Let's summarize:

* We are going to remove poison and all json in favor of module attributes (e.g. `@first_names ["Alex", "John"]`).
* We are going to separate locales in modules (e.g. `Faker.Name.Fr.name`).
* We move json [formats](https://github.com/igas/faker/blob/5e72087db4d071308eddfb0881671f97b3730369/priv/address.json#L3-L7) and [values](https://github.com/igas/faker/blob/5e72087db4d071308eddfb0881671f97b3730369/priv/address.json#L23-L31) to plain functions.
* For [functions](https://github.com/igas/faker/blob/5e72087db4d071308eddfb0881671f97b3730369/priv/address.json#L8-L22) we add some macro which expands to code like this:
```elixir
def city do
  city(:crypto.rand_uniform(0, 2))
end

def city(0) do
  "#{city_prefix} #{Faker.Name.first_name}#{city_suffix}"
end

def city(1) do
  "#{city_prefix} #{Faker.Name.first_name}"
end
```

Right?

Only thing we need to decide is application. I think we need to start application like [amrita](https://github.com/josephwilk/amrita). In `test/test_helper.exs` for example:

```elixir
Faker.start(:fr)
```

**Comment by whatyouhide** [comment]
About the application, so what would be the code for `Faker.start`?

**Comment by igas** [comment]
For now `start/0` just `:application.start(:faker)` to remove it from mix.exs and start it explicit where you need. And `start/1`:

```elixir
def start(lang)
  :application.start(:faker)
  Faker.locale(lang)
end
```

**Comment by whatyouhide** [comment]
Ok, sounds fair.

About removing the Poison dependency and using module attributes to store values, we could just create  simple data files in a plaintext format what we can easily parse inside Faker. I'm not a fan of storing **a lot** of data along with the code in regular modules. What do you think?

**Comment by gazay** [comment]
https://github.com/GIML bros!

**Comment by whatyouhide** [comment]
@gazay I think the point would be to remove all dependencies, but yes, that's a nice alternative solution :). If we have to leave dependencies though I think JSON could be fine at that point.

**Comment by gazay** [comment]
In Haskell you just don't have JSON parser without dependencies (not like in Ruby – it is a part of core lib) and they are pretty heavy. So thats why I wrote my small parser for my small language)) I don't know situation in Elixir, so yes, if it is like Ruby and have JSON parser in core lib - then better use it.

**Comment by whatyouhide** [comment]
No, Elixir doesn't have a JSON parser in the stdlib either. What I was saying is that the purpose of using module attributes should be to completely remove **any** external dependency (such as Poison, the JSON parser that Faker is using). Removing the Poison dependency but adding a dependency to a parser for your language is kind of pointless IMO.

**Comment by igas** [comment]
@whatyouhide The problem with JSON dependency is it more general, lately phoenix framework start using poison and we need to deal with it which I don't like. Coupling on one popular project make problems with others.

**Comment by whatyouhide** [comment]
I agree that **no dependencies** are cleaner that **some dependencies**, but *if* you have to have dependency than I'd rather use a well-known and used project like Poison to parse JSON data than a *very* young (less that 2 months old I think?) and unknown markup language **and** its dependency.

Obviously, you have the final word since you're the owner of the repository. I'm just expressing my opinion here :smile:.

**Comment by igas** [comment]
Let's be _lean_ and decide it later, for now we keep poison only for storing values.
