### ISSUE TITLE
Fake.Internet.email() is not working.

### ISSUE THREAD

**Issue by erneestoc** [igas/faker#128]
I think faker is giving me non valid emails..

`ryann_o'keefe@powlowski.org` is not a valid email format. (I think, tested with my regex and some  online email validators)

The Faker.Internet.email() function should not provide me with wrong data. My tests are crying. 😥

**Comment by tobyhinloopen** [comment]
`ryann_o'keefe@powlowski.org` is a RFC 5322 compliant e-mail address

**Comment by erneestoc** [comment]
Thanks! I'll change my email validator.
