### ISSUE TITLE
UUID support

### ISSUE THREAD

**Issue by anthonator** [igas/faker#135]
It would be great if we could get support for generating UUID's. I currently either use `Ecto.UUID` or the `uuid` package when testing.

I think only v4 UUID's would be necessary.

**Comment by anthonator** [comment]
Would be happy to contribute this

**Comment by igas** [comment]
Hi, contribution welcome. Keep in mind that we are trying to be 0 dependency and you'll need to implement it.

**Comment by anthonator** [comment]
Is there a Faker specific version of `:crypto.strong_rand_bytes/1` you'd like me to use? Didn't see anything obvious in util.ex

**Comment by anthonator** [comment]
https://github.com/igas/faker/pull/137

May need a change depending on the answer to my question above

**Comment by anthonator** [comment]
Let me know what you think of my PR

**Comment by anthonator** [comment]
Would love any feedback when you get a chance

**Comment by igas** [comment]
Closed by #137
