### ISSUE TITLE
Faker.Food API

### ISSUE THREAD

**Issue by vbrazo** [igas/faker#140]
Hello faker community! 

I'm building an API that is going to be used in a mobile application. The goal of this app is to allow grandparents to build their receipts to cook on the weekends. I'm building this app in my spare time to have fun and learn new libraries. I'll eventually publish the app on Apple/Play Store.

I took a look at the docs and saw that we have a `Pizza` module (pretty cool :) I'm already using it), but I couldn't find information about `ingredients` and `dishes`.

Would you guys mind if I add a new module to have this information? I understand that the usage of this module would be restricted to the food category and it would benefit people that are in the same situation as I am. Please let me know if this is a good idea. 

I'm referencing this issue to a PR that I wrote, so you guys can decide whether we could add this new module or not.

Thanks.

**Comment by igas** [comment]
Closed by #141
