### ISSUE TITLE
Add "sku()" to Commerce (or Code?) module

### ISSUE THREAD

**Issue by apeacox** [igas/faker#18]
When dealing with e-commerce, it's almost frequent to need unique [sku](https://en.wikipedia.org/wiki/Stock_keeping_unit). So it might be a good idea to add it to `Commerce` or `Code` modules. I'd put them on the former, but I saw you used the latter for stuff like `isbn`s.

**Comment by igas** [comment]
Hi @apeacox, PR are welcome =) I think it should be `Commerce` cause it doesn't have spec, according to wiki. If you can describe what you need with examples I can do it, but for now I don't know what to do.

**Comment by igas** [comment]
Hey @apeacox, any updates on this one?

**Comment by apeacox** [comment]
well, for now I've abandoned faker package because I've switched from factories to fixtures. so it wasn't a problem to fill in some values by hand.

**Comment by igas** [comment]
@apeacox sure, no worries =)
