### ISSUE TITLE
Release Faker.UUID

### ISSUE THREAD

**Issue by christophermlne** [igas/faker#195]
https://github.com/igas/faker/issues/151

**Comment by igas** [comment]
Hi guys,

I've been busy with some personal stuff lately and was not able to finish rewrite of our codebase to new approach, this is the reason why this was not released yet.

We have 2 options here, I can do quick release `0.10.1` with `UUID` or you can use `{:faker, github: "igas/faker"}`.

I'm courious if you have any problems with the second option?

**Comment by anthonator** [comment]
I'm sure we all understand that life happens. I appreciate you taking the time to address this.

My vote would be to do a release. We have a policy which prevents us from pulling dependencies from source control.

**Comment by vbrazo** [comment]
My vote would be to do a release +1

**Comment by igas** [comment]
I decided to do 0.11.0, thought about `0.11.0-rc.0`, but sounded silly. I'm sure we would need a few minor releases to finish the cleanup. Meanwhile please feel free to rise up issues if something is broken.
