### ISSUE TITLE
Faker.Internet.Email

### ISSUE THREAD

**Issue by jasontwong** [igas/faker#199]
Why do you generate emails that don't match specs?

for example: `pearline_o'conner@schuster.org`

**Comment by vbrazo** [comment]
Do you wanna create a patch for this issue?

**Comment by vbrazo** [comment]
@jasontwong I just opened a PR. Lemme know what you think about my changes.

**Comment by igas** [comment]
Hi @jasontwong,

I don't know which spec you are referring to, but your example is a valid address according to [rfc5322](http://www.ietf.org/rfc/rfc5322.txt).
