### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anthonator** [igas/faker#231]
Heeey

I hate to be that guy but is there any way we could cut a new release? I see the Elixir 1.8 DateTime deprecations have been fixed in `master`. The deprecation warnings flooding my test suite are driving me a bit crazy.

Would be happy to help push anything along that's preventing a release.

**Comment by anthonator** [comment]
Just want to check in on this. Any possibility of making this happen? Again, I'm happy to help push anything along that's preventing a release.

**Comment by DavidVII** [comment]
I'd love to see a new release to remove these warnings. I'm happy to help as well 👍

**Comment by anthonator** [comment]
Would it be possible to get a response to this?

**Comment by igas** [comment]
Closed via #239
