### ISSUE TITLE
Consider adding additional maintainers

### ISSUE THREAD

**Issue by anthonator** [igas/faker#236]
I propose adding additional maintainers to this project.

This project is pretty popular (almost 200k downloads on hex.pm) but attention to contributor issues and PR's seems to be lacking. We all understand that life happens and projects you _volunteer_ your time to aren't always a priority. I think it would be beneficial to the community to add additional maintainers so the burden of maintaining this package doesn't fall completely to @igas. As a contributor to this project I'd be happy to help with minor issues and PR's. I'd also nominate @vbrazo if he'd be interested.

I just want to note that this is not meant to be any sort of negative commentary on @igas. I think he's done a great job with this project and I've enjoyed using it extensively. I use and care about this project and want to ensure that it has the support it needs to be successful.

**Comment by vbrazo** [comment]
I'd be happy to be a collaborator and start contributing more to this library. I've merged some good PRs so far, and I believe we still have a lot to do. I'd prefer to work with other collaborators to discuss PRs and ideas. @igas and I worked together in a few tasks last year and it was pretty awesome. 

Let's just build this library together!

**Comment by igas** [comment]
Hi guys,

I'm happy to do this and I've done this before with @tobyhinloopen.

I actually thought about writing the email to @vbrazo regarding this, but @anthonator done this for me ;)

I propose the following:

I'll add both of you to github collaborators as I remember your interest from PRs and issues.

Regarding changes itself, feel free to review and merge all new locales and data related modules, as well as elixir/erlang related deprecations (please stick with https://keepachangelog.com/ and 1 commit per PR).

Please consult me through new modules to have an agreement on API and taxonomy proposed in https://github.com/igas/faker/issues/208. This is not about trust, it's just I have some thoughts over 5 years I've been doing faker in elixir that I still want to implement/discuss to leverage elixir functionalities and not just port data from other languages.

I'm also the only maintainer on hex for now, so when we need to cut release just drop me an email or any other communication we find working for us.

I don't use email notification as I'm also one of core maintainer of homebrew, this would be too many emails for me, this is why I use https://octobox.io/ but don't check it regularly enough lately. So, this and real-life contributed to the lack of transparency for this project for me. So if you need my attention, drop me an email and I'll get back to you. This does not mean I'm not interested in the project, quite contrary, it's just hard for me right now to find time for it.

Of course, if I would be still lacking focus on the project or disappear we'll discuss it further to change some of the proposals above.

For now, if you agree with this pls submit PR about adding you as maintainers and we'll cut the release.

If you feel like what I'm proposing is not fair or have any other concerns do not hesitate to reply with feedback. Last thing I want to be compromising future of the project and discourage contributions.

**Comment by vbrazo** [comment]
Sounds good to me @igas @anthonator

**Comment by anthonator** [comment]
Sounds good to me as well! Thanks for being open to this @igas! Let me know the best email to reach you at. I'd love to see a new release cut to fix the 1.8 deprecation warnings.
