### ISSUE TITLE
Out of date documentation on Hexdocs

### ISSUE THREAD

**Issue by jjl** [igas/faker#244]
Looks like it didn't push correctly, because I can't see the `Faker.DateTime` namespace.

**Comment by anthonator** [comment]
The documentation is up to date. The `Faker.DateTime` module is set to `@moduledoc false`.

https://github.com/igas/faker/blob/master/lib/faker/datetime.ex#L2

I'm not sure why. @igas any ideas?

**Comment by anthonator** [comment]
Looks like it got added here.

https://github.com/igas/faker/commit/34b91ee2a37192c728ee4cf1dda5026d71ec63d3#diff-f68672b91b8c7896852f3cfafa62a96d

**Comment by jalcine** [comment]
I almost added a pull-request for this. But it seems like one should to remove that `@moduledoc` bit up there.

(Originally published at: https://v2.jacky.wtf/post/a065438f-464b-4c05-9787-0f0fc3778936)

**Comment by anthonator** [comment]
@jalcine PR's are always welcome!

**Comment by jalcine** [comment]
Just opened a PR for this! https://github.com/igas/faker/pull/249.

(Originally published at: https://v2.jacky.wtf/post/e6864b76-0af2-44f4-9877-a595ec031bdc)
