### ISSUE TITLE
Pass all random number generation through a single function

### ISSUE THREAD

**Issue by andruby** [igas/faker#37]
I often want random, but deterministic fake data for seeds. This is great because the generated data is always the same on all machines that run the seeds.

If all random number generation uses a single function, library users could swap `:crypto.rand_uniform` with a seeded RNG. 

@igas does this sound like a good idea?

**Comment by igas** [comment]
Sounds interesting. I'll be glad to merge it if implementation will be simple and elegant. It also can help with faker tests itself. Do you have implementation ideas? I'm thinking about something like [this](http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/)

**Comment by igas** [comment]
Hi @andruby, if you still interested, please take a look at #101
