### ISSUE TITLE
What about an Helper module ?

### ISSUE THREAD

**Issue by GesJeremie** [igas/faker#50]
It would be awesome to have an Helper module:

```
Faker.Helper.pick ~w(jeremie peter laurent) #=> "peter"
```

Internally we have an awesome macro :sampler, I think it will be useful to provide an api for the developers ?!

I really liked another feature from Mirage (it's an npm / ember module to fake a REST API into the client):

```
Faker.Helper.cycle ~w(jeremie peter laurent henry frank zombie) 

#=> Everytime the function is called, it returns the next value in the list, 
#=> when it reachs the end, you just loop again the cycle.
#=> Really awesome when you seed a database
```

**Comment by igas** [comment]
Yes, I had a thoughts about both of them.

* I want to move most of Faker module to Helper, I don't think we need pick, sampler should do the job on compile time, but you need to use it a little bit differently.

* That's great, I also want something like this, but more like `uniq`. Say I'm testing user list, and creating 1000 users, with uniq name validation, sometimes test fails cause of validation.

**Comment by tobyhinloopen** [comment]
What's wrong woth Enum.random?

**Comment by tobyhinloopen** [comment]
@igas We have `Faker.Util.pick` by now. Is there a reason to keep this issue open?
