### ISSUE TITLE
Deprecated random module

### ISSUE THREAD

**Issue by kiaking** [igas/faker#56]
Since Elixir 1.3 (I guess) the `random` module has been deprecated. Hence we get these warning when compiling Faker.

```console
warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/avatar.ex:43
...
```

Would it be helpful if I make PR to replace random module with rand module? Or is there any concern?

**Comment by igas** [comment]
Hi, thanks, it's been done in #53. Sadly don't have time to fix this and release new version.

**Comment by kiaking** [comment]
Oh sorry I didn't see that. Thanks! Hope you can find some time : )
