### ISSUE TITLE
Faker.Internet.email does not work

### ISSUE THREAD

**Issue by uri** [igas/faker#57]
```
iex(1)> Faker.Internet.email
** (UndefinedFunctionError) function :"Elixir.Faker.Name.".first_name/0 is undefined (module :"Elixir.Faker.Name." is not available)
    :"Elixir.Faker.Name.".first_name()
    lib/faker/internet.ex:31: Faker.Internet.user_name/1
    lib/faker/internet.ex:45: Faker.Internet.email/0
```

**Comment by igas** [comment]
Hi @uri, you forgot to start app check out https://github.com/igas/faker#usage TL;DR in your iex session you can run `Faker.start`

**Comment by denispeplin** [comment]
Not very clear from docs, it will be nice to have an example on a separate line.

**Comment by igas** [comment]
@denispeplin @uri PR is welcome. I tried to clarify this few times, but issues like this still happen.

**Comment by jonchoukroun** [comment]
Hi @igas I know you closed this issue, but I can't find the solution to this anywhere. How can I start the faker app in priv/repo/seeds.exs? I'm happy to write a PR with additional documentation if I figure it out.

**Comment by tobyhinloopen** [comment]
@jonchoukroun Just a thought, but did you try adding `Faker.start` at the top of your seeds file?

**Comment by jonchoukroun** [comment]
@tobyhinloopen thanks for the advice, but that didn't work. I did solve it, though, by adding
`import Faker`
then calling it as if it had been aliased, like so:
`username: Faker.Internet.username`

@igas, I would be happy to make a PR for readme, maybe to add an example for using Faker in seeds.exs. Let me know if that's helpful.

Thanks for the help.

**Comment by dokicro** [comment]
@jonchoukroun I tried to da `import Faker` as you recommended but I get this error: `module Faker is not loaded and could not be found`

**Comment by uri** [comment]
@dokicro are you running `import Faker` in an `iex` session?

**Comment by jonchoukroun** [comment]
@dokicro You have to include `Faker` in your dependencies. Inside `mix.exs` in your application's root, find the private function `deps/0` which returns a list of tuples. You'll want to include Faker as one of those, then run `mix deps.get` at the command line.

Inside `/priv/repo/seeds.exs` you'll add `import Faker` and that lets you call it as `Faker.Internet.user_name`. Hope this helps.
