### ISSUE TITLE
Should not try to randomly access a list

### ISSUE THREAD

**Issue by uri** [igas/faker#58]
It seems like the core mechanism is this library is to use the `sampler` macro to define a function that access a giant **_list**_ at a random index. Lists are not meant for random access, they are slow and your access time is linear.

Keeping inline with the current mechanism, the sampler macro should be provided a giant _tuple_ instead of a list. The macro itself would need to use `elem` to access the tuple instead of `[]`.

**Comment by igas** [comment]
Hi @uri,

you are right, but I think we'll switch to `map`, cause in our ticket we already discussed it and decided to have erlang 18+.

**Comment by uri** [comment]
Awesome! When I was writing this ticket I wasn't sure which would make more sense: using a tuple or a map. Was there any discussion around this? I'm assuming for a map you would do something like `%{1 => "Abbie", 2=> "Abbigale" ...}`or would it be implemented differently?

**Comment by igas** [comment]
@uri, I think I implemented it. I left API the same, but at compile time it does a transformation. Take a look at #68.
