### ISSUE TITLE
Documentation summary README removed

### ISSUE THREAD

**Issue by GesJeremie** [igas/faker#59]
Can you explain me why you just removed the whole documentation I did ?
 
https://github.com/igas/faker/commit/59e2bb41ce60e5c8b09cc7ab6e09e83edbd47398

I wanted to use the library to create some factories in my current application today. 

The documentation we have is quite poor (we don't see the ouput of the different methods), that's why I spent 1hour 1 month ago to do this tiny documentation in the README. Nobody want to overthink, they just want a brief in the README what they can use and what it outputs.

Anyway, I'm really sad and I'm waiting for your reply.

**Comment by igas** [comment]
Hi @GesJeremie,

my intention was around issues that appear quite regularly around misunderstanding how to use (start) lib in the first place #57, #19, #7. I thought if we make readme smaller it'll help ppl to find how to do it, coz it's there but they miss it.

I see 3 possible solutions:
* improve docs in hex;
* move work you done in CHEATSHEET.md or USAGE.md or similar and have link in readme;
* accept that I made the mistake and put it back if ppl say so (I see already 2 ppl need it).

> Nobody want to overthink

I completely agree, but we also need a balance between ppl who already knows how to use it and they need something from subject and ppl who need getting started.

> Anyway, I'm really sad and I'm waiting for your reply.

I'm really sorry about that.

**Comment by GesJeremie** [comment]
Just saw you put it back in a separate usage file, sounds good to me ;)
