### ISSUE TITLE
Argument error in Faker.format/2

### ISSUE THREAD

**Issue by anronin** [igas/faker#62]
Hi! I have some strange problem with `Faker.format` when i run it with hashtag string:
```
iex> Faker.format("#")
** (ArgumentError) argument error
    (faker) lib/faker.ex:35: Faker.format/2
```
I think problem may be with new OTP 19 version. 
I have this environment:

Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit]
Elixir 1.4.0-dev (f7c699f)

**Comment by pauloancheta** [comment]
I just tried it with my environment and it returns what is expected.
I am using:
Erlang/OTP 19 [erts-8.0.2]
Elixir 1.3.2 and 1.3.3

**Comment by igas** [comment]
Hi @anronin, I've just checked:

```
mix new ftest
# set deps in mix.exs
  defp deps do
    [{:faker, ">= 0.0.1"}]
  end
mix deps.get
iex -S mix
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.4.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Faker.format("#")
"9"
```

Do you still have a problem with it? can you show steps to reproduce?

**Comment by anronin** [comment]
sorry for late answer, now i think that problem maybe in my phoenix application, because i've just pulled `faker` from git and everything work just fine. my bad
