### ISSUE TITLE
Can we add the #Hacktoberfest label for pull requests this month

### ISSUE THREAD

**Issue by orieken** [igas/faker#63]
👍 #Hacktoberfest https://hacktoberfest.digitalocean.com/

**Comment by igas** [comment]
I'm not sure I understand it completely, but I'm ok with this kind of promo.

**Comment by orieken** [comment]
We would just have to add a Hacktoberfest label to the to issues, https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by igas** [comment]
👍
