### ISSUE TITLE
function Faker.Date.date_of_birth/1 is undefined

### ISSUE THREAD

**Issue by adrianotadao** [igas/faker#78]
I don't know what is happening but I can't use the all the `Faker.Date` methods.

```
iex(5)> Faker.Date.date_of_birth(10..19)
** (UndefinedFunctionError) function Faker.Date.date_of_birth/1 is undefined (module Faker.Date is not available)
    Faker.Date.date_of_birth(10..19)
```

does anyone have some idea why?

**Comment by tobyhinloopen** [comment]
What version of Faker are you using?
What version of Elixir are you using?

date_of_birth is a very recent addition and is only enabled for Elixir >=1.3 IIRC

**Comment by adrianotadao** [comment]
@tobyhinloopen Hello, my versions are:

```
# Elixir
➜  ~ elixir --version
Elixir 1.4.1
```

```
# Version
:faker, "~> 0.7"
```

**Comment by igas** [comment]
I think you are using hex version of faker. This Date module part of unreleased version: https://github.com/igas/faker/blob/master/CHANGELOG.md

You can change you dependency to get latest version from github if you want.

**Comment by adrianotadao** [comment]
hummmmmm @igas make sense. Thank you and my apologies. I'm so dumb. xD

**Comment by igas** [comment]
@adrianotadao no worries, it's my fault, I have a plans for this version and don't have much time right now =(

@tobyhinloopen thank you. For all help in recent issues and PRs.
