### ISSUE TITLE
Add slug generator

### ISSUE THREAD

**Issue by anthonator** [igas/faker#79]
Generate a URL safe slug. I think this could fall under the `Internet` namespace.

Example: `this-is-a-slug`

I'd be happy to tackle this if you think it would be valuable.

**Comment by igas** [comment]
Yep, sounds good.

Ruby faker API looks reasonable:
```ruby
# Optional arguments: words=nil, glue=nil
Faker::Internet.slug #=> "pariatur_laudantium"
Faker::Internet.slug('foo bar') #=> "foo.bar"
Faker::Internet.slug('foo bar', '-') #=> "foo-bar"
```

**Comment by tobyhinloopen** [comment]
In the ruby example, I don't get why the default case with 0 arguments, the slugs are "glued" with `_` and the 2nd example, glued with `.`. Is the "glue" random as well? I feel like `-` should be default.

But +1 for this addition

**Comment by anthonator** [comment]
@tobyhinloopen if you fixed it to a `-` how would you randomize it if that's what you wanted?

**Comment by anthonator** [comment]
This is my first attempt.

https://github.com/igas/faker/pull/80

I kept it pretty close to the Ruby implementation. The biggest difference is that you need to provide a list for the glue. This way we can provide a custom random glue.

**Comment by igas** [comment]
@tobyhinloopen I feel that `-` is most common. but I feel like in this one better to have random, so ppl can find that they do not handle all the cases in specs for example, if they have their own slug format, they can get it with this. Thoughts?

**Comment by tobyhinloopen** [comment]
@igas Sounds right 👍
