### ISSUE TITLE
Calling Faker into spawn

### ISSUE THREAD

**Issue by itSQualL** [igas/faker#81]
I'm using `Faker` to generate my seeds into a `Phoenix` project. I'm using `spawn_link` to improve speed, but, for any reason, `Faker` stops working into the new processes. 

What could be happening?

**Comment by igas** [comment]
Hi, faker does not use processes, so you can't spawn it. Plus it won't be faster. Faker just use plain functions.

Pls provide an example if I misunderstood you.

**Comment by itSQualL** [comment]
Thank you for the info!
