### ISSUE TITLE
Pokemon and Superheros are not included in 0.7.0

### ISSUE THREAD

**Issue by neneboe** [igas/faker#82]
Here is a screenshot of the faker directory in my deps. I have confirmed that I have version 0.7.0.

![image](https://cloud.githubusercontent.com/assets/1339824/23826297/95c2e156-064e-11e7-9ce5-b3f5c4262ad6.png)

**Comment by igas** [comment]
hi @neneboe, sorry for confusion, this 2 modules in unreleased version, pls take a look at: https://github.com/igas/faker/blob/master/CHANGELOG.md

you can use github version in dependency if you want.

**Comment by neneboe** [comment]
Oops, sorry, didn't see that. Thanks!
