### ISSUE TITLE
Update hex.pm version

### ISSUE THREAD

**Issue by yordis** [igas/faker#83]
I just installed `faker: 0.7.0` which I couldn't use `Faker.Date` because it wasn't there.

@igas could you please publish some new version of `Faker` to `hex.pm` 👏

**Comment by igas** [comment]
I checked one more time, it would be good to finalise #74 before doing release. You offered help there, if you can pick it up it would be good. Thanks.

**Comment by yordis** [comment]
@igas yes I like that idea! I need that too 😄

**Comment by anthonator** [comment]
Is #74 necessary to cut a new version? I'd like to start using the slug generator I put together last month. There doesn't seem to be much traction in getting it resolved so I'm wondering if we could get away without it.

**Comment by igas** [comment]
@anthonator you can use `{:faker, github: "igas/faker"}` and get it today.
@yordis any update on #74?

**Comment by anthonator** [comment]
Is there any way we can get a new version out since #74 has been resolved?
