### ISSUE TITLE
Always have parentheses in function calls to avoid warnings

### ISSUE THREAD

**Issue by petejkim** [igas/faker#89]
Is this something we want to fix (to hush warnings) or are you philosophically against the change?

<img width="1312" alt="screen shot 2017-04-26 at 11 38 42 am" src="https://cloud.githubusercontent.com/assets/30173/25450815/fcf51656-2a74-11e7-9253-0fb15feb62fc.png">

**Comment by igas** [comment]
hey, it's been fixed, but no new version release yet... meanwhile you can use github version as dependency if you want.

**Comment by petejkim** [comment]
Thanks!
