### ISSUE TITLE
Add a user-agent generator

### ISSUE THREAD

**Issue by tobyhinloopen** [igas/faker#93]
It appears we don't have a `Faker.Internet.user_agent` - could be handy.

Example:

`Faker.Internet.user_agent #=> "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"`

It could either return a predefined set of real user-agents or could generate fake ones based on common keywords, browser names, OS names and random digits, consisting of N samples joined with ` ` (space) from patterns like below:

`$vendor_name/$version`
`($vendor_name $version)`
`($keyword, like $keyword)`

**Comment by igas** [comment]
Hey @tobyhinloopen, great idea! Lets go with real ones.

**Comment by tobyhinloopen** [comment]
Reminder to self, use a list like https://github.com/joecampo/random-user-agent/blob/master/src/agents/agent_list.json

**Comment by GustavoCaso** [comment]
@tobyhinloopen I would like to help with this one. Also I have been playing with elixir for a while and I would like to start contributing back to the community

**Comment by tobyhinloopen** [comment]
@GustavoCaso Feel free to do so. You can implement it if you like

**Comment by GustavoCaso** [comment]
@tobyhinloopen looks like is already been implemented https://github.com/igas/faker/blob/master/lib/faker/internet/user_agent.ex
😢 😄 you can close the issue
