### ISSUE TITLE
crypto:rand_uniform/2 is deprecated

### ISSUE THREAD

**Issue by sofianegargouri** [igas/faker#99]
Hi,

I just installed Faker in my Phoenix project, and I got this warning a lot of time. Guess it was worth an issue.

![image](https://user-images.githubusercontent.com/4323986/28271751-548bbdf8-6b01-11e7-95d1-489a4473fb1a.png)

**Comment by igas** [comment]
@sofianegargouri Hi, yes, on OPT 20 this function deprecated. I hope to fix it through https://github.com/igas/faker/tree/predictable-random-proposal

**Comment by julien-leclercq** [comment]
Hi @igas what's missing for the merge to be done ? Maybe we can help ?

**Comment by igas** [comment]
@sofianegargouri @julien-leclercq please take a look at #101 Feedback and test of this branch in your projects would be much appreciated.

**Comment by julien-leclercq** [comment]
ok, i am a bit busy this week but i'll try to have a look in my spare time :)

**Comment by yordis** [comment]
@igas is this done yet? I can work on my time for resolve this, it seems to be straight forward

**Comment by igas** [comment]
@yordis I have proposal solution in https://github.com/igas/faker/pull/101 feel free to give feedback.

**Comment by tobyhinloopen** [comment]
All references to `:crypto.rand_uniform` are not removed
